name: Dependabot Auto-Merge

on:
  pull_request_target:
    types: [labeled, edited, synchronize, opened, reopened]

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    # Nur ausführen, wenn der PR von Dependabot stammt
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Automerge Dependabot PR
        uses: iobroker-bot-orga/action-automerge-dependabot@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
